# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: thheller/cljs-dev:latest

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-deps-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - m2-deps-

      - run: yarn install

      - save_cache:
          paths:
            - ~/.m2
          key: m2-deps-{{ checksum "project.clj" }}

      - run: shadow-cljs compile test

      - run: cd out

      - run: node node-tests.js
