# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:openjdk-8-tools-deps-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npx shadow-cljs -A:dev -v compile test
      - run: cd out
      - run: node node-tests.js
